In [1]:
import pandas as pd

In [2]:
import numpy as np

In [15]:
data=pd.read_csv('fifa.csv')

In [16]:
data.head(10)

,team1,team2,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,date,hour,category,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
0,QATAR,ECUADOR,42%,50%,8%,0,2,20 NOV 2022,17 : 00,Group A,...,0,1,6,5,0,0,52,72,256,279
1,ENGLAND,IRAN,72%,19%,9%,6,2,21 NOV 2022,14 : 00,Group B,...,0,1,8,13,0,0,63,72,139,416
2,SENEGAL,NETHERLANDS,44%,45%,11%,0,2,21 NOV 2022,17 : 00,Group A,...,0,0,9,15,0,0,63,73,263,251
3,UNITED STATES,WALES,51%,39%,10%,1,1,21 NOV 2022,20 : 00,Group B,...,0,1,7,7,0,0,81,72,242,292
4,ARGENTINA,SAUDI ARABIA,64%,24%,12%,1,2,22 NOV 2022,11 : 00,Group C,...,1,0,4,14,0,0,65,80,163,361
5,DENMARK,TUNISIA,55%,33%,12%,0,0,22 NOV 2022,14 : 00,Group D,...,0,0,11,11,0,0,76,73,226,287
6,MEXICO,POLAND,54%,31%,15%,0,0,22 NOV 2022,17 : 00,Group C,...,0,0,8,15,0,0,61,70,193,290
7,FRANCE,AUSTRALIA,56%,35%,9%,4,1,22 NOV 2022,20 : 00,Group D,...,0,0,4,22,0,0,64,56,250,316
8,MOROCCO,CROATIA,32%,57%,12%,0,0,23 NOV 2022,11 : 00,Group F,...,0,0,7,8,0,0,87,58,391,217
9,GERMANY,JAPAN,65%,22%,13%,1,2,23 NOV 2022,14 : 00,Group E,...,1,0,12,26,0,0,55,87,164,487

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 88 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   team1                                                  64 non-null     object
 1   team2                                                  64 non-null     object
 2   possession team1                                       64 non-null     object
 3   possession team2                                       64 non-null     object
 4   possession in contest                                  64 non-null     object
 5   number of goals team1                                  64 non-null     int64
 6   number of goals team2                                  64 non-null     int64
 7   date                                                   64 non-null     object
 8   hour                                                   64 non-null     object
 9   category                                               64 non-null     object
 10  total attempts team1                                   64 non-null     int64
 11  total attempts team2                                   64 non-null     int64
 12  conceded team1                                         64 non-null     int64
 13  conceded team2                                         64 non-null     int64
 14  goal inside the penalty area team1                     64 non-null     int64
 15  goal inside the penalty area team2                     64 non-null     int64
 16  goal outside the penalty area team1                    64 non-null     int64
 17  goal outside the penalty area team2                    64 non-null     int64
 18  assists team1                                          64 non-null     int64
 19  assists team2                                          64 non-null     int64
 20  on target attempts team1                               64 non-null     int64
 21  on target attempts team2                               64 non-null     int64
 22  off target attempts team1                              64 non-null     int64
 23  off target attempts team2                              64 non-null     int64
 24  attempts inside the penalty area team1                 64 non-null     int64
 25  attempts inside the penalty area  team2                64 non-null     int64
 26  attempts outside the penalty area  team1               64 non-null     int64
 27  attempts outside the penalty area  team2               64 non-null     int64
 28  left channel team1                                     64 non-null     int64
 29  left channel team2                                     64 non-null     int64
 30  left inside channel team1                              64 non-null     int64
 31  left inside channel team2                              64 non-null     int64
 32  central channel team1                                  64 non-null     int64
 33  central channel team2                                  64 non-null     int64
 34  right inside channel team1                             64 non-null     int64
 35  right inside channel team2                             64 non-null     int64
 36  right channel team1                                    64 non-null     int64
 37  right channel team2                                    64 non-null     int64
 38  total offers to receive team1                          64 non-null     int64
 39  total offers to receive team2                          64 non-null     int64
 40  inbehind offers to receive team1                       64 non-null     int64
 41  inbehind offers to receive team2                       64 non-null     int64
 42  inbetween offers to receive team1                      64 non-null     int64
 43  inbetween offers to receive team2                      64 non-null     int64
 44  infront offers to receive team1                        64 non-null     int64
 45  infront offers to receive team2                        64 non-null     int64
 46  receptions between midfield and defensive lines team1  64 non-null     int64
 47  receptions between midfield and defensive lines team2  64 non-null     int64
 48  attempted line breaks team1                            64 non-null     int64
 49  attempted line breaks team2                            64 non-null     int64
 50  completed line breaksteam1                             64 non-null     int64
 51  completed line breaks team2                            64 non-null     int64
 52  attempted defensive line breaks team1                  64 non-null     int64
 53  attempted defensive line breaks team2                  64 non-null     int64
 54  completed defensive line breaksteam1                   64 non-null     int64
 55  completed defensive line breaks team2                  64 non-null     int64
 56  yellow cards team1                                     64 non-null     int64
 57  yellow cards team2                                     64 non-null     int64
 58  red cards team1                                        64 non-null     int64
 59  red cards team2                                        64 non-null     int64
 60  fouls against team1                                    64 non-null     int64
 61  fouls against team2                                    64 non-null     int64
 62  offsides team1                                         64 non-null     int64
 63  offsides team2                                         64 non-null     int64
 64  passes team1                                           64 non-null     int64
 65  passes team2                                           64 non-null     int64
 66  passes completed team1                                 64 non-null     int64
 67  passes completed team2                                 64 non-null     int64
 68  crosses team1                                          64 non-null     int64
 69  crosses team2                                          64 non-null     int64
 70  crosses completed team1                                64 non-null     int64
 71  crosses completed team2                                64 non-null     int64
 72  switches of play completed team1                       64 non-null     int64
 73  switches of play completed team2                       64 non-null     int64
 74  corners team1                                          64 non-null     int64
 75  corners team2                                          64 non-null     int64
 76  free kicks team1                                       64 non-null     int64
 77  free kicks team2                                       64 non-null     int64
 78  penalties scored team1                                 64 non-null     int64
 79  penalties scored team2                                 64 non-null     int64
 80  goal preventions team1                                 64 non-null     int64
 81  goal preventions team2                                 64 non-null     int64
 82  own goals team1                                        64 non-null     int64
 83  own goals team2                                        64 non-null     int64
 84  forced turnovers team1                                 64 non-null     int64
 85  forced turnovers team2                                 64 non-null     int64
 86  defensive pressures applied team1                      64 non-null     int64
 87  defensive pressures applied team2                      64 non-null     int64
dtypes: int64(80), object(8)
memory usage: 44.1+ KB

In [10]:
data.describe()

,number of goals team1,number of goals team2,total attempts team1,total attempts team2,conceded team1,conceded team2,goal inside the penalty area team1,goal inside the penalty area team2,goal outside the penalty area team1,goal outside the penalty area team2,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
count,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,...,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000
mean,1.578125,1.109375,11.140625,11.281250,1.109375,1.578125,1.468750,0.984375,0.093750,0.109375,...,0.140625,0.125000,11.593750,11.359375,0.015625,0.015625,71.968750,70.125000,289.750000,293.265625
std,1.551289,1.055856,4.972519,5.807682,1.055856,1.551289,1.563155,0.999876,0.293785,0.314576,...,0.350382,0.377964,5.911299,4.990045,0.125000,0.125000,14.394629,13.531269,88.406888,80.916230
min,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,38.000000,44.000000,139.000000,141.000000
25%,0.000000,0.000000,8.000000,7.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,7.750000,8.000000,0.000000,0.000000,63.000000,60.250000,229.000000,233.750000
50%,1.000000,1.000000,10.000000,10.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,11.000000,10.000000,0.000000,0.000000,71.000000,72.000000,281.000000,292.500000
75%,2.000000,2.000000,14.000000,14.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,14.000000,14.000000,0.000000,0.000000,83.500000,79.000000,328.000000,327.500000
max,7.000000,4.000000,25.000000,32.000000,4.000000,7.000000,7.000000,4.000000,1.000000,1.000000,...,1.000000,2.000000,32.000000,26.000000,1.000000,1.000000,101.000000,104.000000,637.000000,585.000000

In [17]:
data.head()

,team1,team2,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,date,hour,category,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
0,QATAR,ECUADOR,42%,50%,8%,0,2,20 NOV 2022,17 : 00,Group A,...,0,1,6,5,0,0,52,72,256,279
1,ENGLAND,IRAN,72%,19%,9%,6,2,21 NOV 2022,14 : 00,Group B,...,0,1,8,13,0,0,63,72,139,416
2,SENEGAL,NETHERLANDS,44%,45%,11%,0,2,21 NOV 2022,17 : 00,Group A,...,0,0,9,15,0,0,63,73,263,251
3,UNITED STATES,WALES,51%,39%,10%,1,1,21 NOV 2022,20 : 00,Group B,...,0,1,7,7,0,0,81,72,242,292
4,ARGENTINA,SAUDI ARABIA,64%,24%,12%,1,2,22 NOV 2022,11 : 00,Group C,...,1,0,4,14,0,0,65,80,163,361

In [19]:
data.shape

(64, 88)

In [26]:
newdf = data[(data.team1 == "QATAR")]

In [27]:
newdf.head

<bound method NDFrame.head of     team1    team2 possession team1 possession team2 possession in contest  \
0   QATAR  ECUADOR              42%              50%                    8%
17  QATAR  SENEGAL              42%              48%                   10%

    number of goals team1  number of goals team2         date     hour  \
0                       0                      2  20 NOV 2022  17 : 00
17                      1                      3  25 NOV 2022  14 : 00

   category  ...  penalties scored team1  penalties scored team2  \
0   Group A  ...                       0                       1
17  Group A  ...                       0                       0

    goal preventions team1  goal preventions team2  own goals team1  \
0                        6                       5                0
17                      12                      11                0

    own goals team2  forced turnovers team1  forced turnovers team2  \
0                 0                      52                      72
17                0                      67                      67

    defensive pressures applied team1  defensive pressures applied team2
0                                 256                                279
17                                308                                232

[2 rows x 88 columns]>

The analysis of the FIFA 2022 dataset reveals that the first team in the match had scored the maximum goals compared to the second. The maximum goals scored by the first team was 7 and second team was 4. 75% of the matches had atleast 2 goals scored by both teams. Maximum of 2 penalties were scored in a single match by the second team. Of all the matches, there were 2 self goals.